#!/bin/bash

# name: Domain
# description: Hostgroup provider based on domain names. Simply groups all hosts by domain.

echo "$HOST_LIST" |\
xargs -n 1 |\
grep -v "^[^.]*$" |\
sed 's/^\([^.]*\.\(.*\)\)/Domain::\2 \1/'
