#!/bin/bash

# name: Domain
# description: Hostgroup provider based on domain names. Simply groups all hosts by domain.

cat $RESULT_DIR/.hosts |\
xargs -n 1 |\
grep -v "^[^.]*$" |\
sed 's/^\([^.]*\.\(.*\)\)/Domain::\2 \1/'
