#!/bin/bash

# name: Mcollective Role Fact
# description: Fetch Host Role from a Mcollective fact. This requires a 1-to-1 host/role mapping available via an Mcollective reported fact. The name of the fact is configurable via $MCOLLECTIVE_ROLE_FACT (default is "role")

if [ "$MCOLLECTIVE_ROLE_FACT" != "" ]; then
# Run with 3 retries, as mcollective is quite unreliable
i=1
while [ $i -lt 3 ]; do
	mco inventory -t 15 --script <(echo "
	inventory do
	  format 'Role::%s %s'
	  fields { [ facts['$MCOLLECTIVE_ROLE_FACT'], identity ] }
	end
	") | grep -v "Role:: "
	i=$((i + 1))
done | sort | uniq
fi
