#!/bin/bash

# name: Primary-Network
# description: Hostgroup provider based on the primary network inventory scanner. Allows grouping by internal networks

if [ -d "$RESULT_DIR" ]; then
	for f in ${RESULT_DIR}/*; do
		sed "/Network INVENTORY ...Primary Net/!d;s/.* /Primary-Network::/;s/\$/ ${f/*\/}/" $f
	done | grep -v ":: "
fi
