#!/bin/bash

# name: PreviousDay
# description: Result directory base host list provider. Provides all still resolvable hosts that were in the previous result set. Using this provider along with a primary CM based source helps to track hosts that are somehow lost to the CM

if [ -d "$RESULT_BASE_DIR/$ONE_DAY_AGO" ]; then
	cd "$RESULT_BASE_DIR/$ONE_DAY_AGO" || exit
	ls | while read name; do
		if [ "$(dig +short $name)" != "" ]; then
			echo $name
		fi
	done
else
	printf "No previous day data found!\n" >&2
fi
