#!/bin/bash

# name: PreviousDay
# description: Result directory base host list provider. Provides resolvable hosts of that were in the previous result set. Using this provider along with a primary CM based source helps to track hosts that are somehow lost to the CM

# Resolve "latest" link into directory name
if [ -d "$RESULT_BASE_DIR/latest" ]; then
	dir=$(readlink -e "$RESULT_BASE_DIR/latest")
	cd $dir || exit
	ls | while read name; do
		if [ "$(dig +short $name)" != "" ]; then
			echo $name
		fi
	done
else
	printf "No previous day data found!\n" >&2
fi
